
CREATE TABLE CLIENTE(
CLIENTEID INT NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY(CLIENTEID)
);
GO


CREATE TABLE PEDIDO(
	PEDIDOID INT NOT NULL PRIMARY KEY,
	CLIENTEID INT NOT NULL,
	IMPORTE MONEY NOT NULL,
	CONSTRAINT FK_PEDIDO_CLIENTE
		FOREIGN KEY (CLIENTEID) REFERENCES CLIENTE(CLIENTEID)
		ON UPDATE CASCADE
		ON DELETE NO ACTION
);
GO


INSERT INTO CLIENTE VALUES(100,'CLIENTE ALFA');
INSERT INTO CLIENTE VALUES(200,'CLIENTE BETA');
GO

INSERT INTO PEDIDO VALUES(1,100,5000);
INSERT INTO PEDIDO VALUES(2,100,8000);
GO


SELECT * FROM CLIENTE;
SELECT * FROM PEDIDO;
GO

UPDATE CLIENTE SET CLIENTEID = 500 WHERE CLIENTEID = 100;
GO

DELETE FROM CLIENTE WHERE CLIENTEID = 500;
GO

DELETE FROM CLIENTE WHERE CLIENTEID = 200;
GO