-- CASO 1

CREATE TABLE TRIPULACION(
	IDPROGRAMACION INT NOT NULL,
	IDTRABAJADOR INT NOT NULL,
	COMENTARIO VARCHAR(500)
);
GO


INSERT INTO TRIPULACION VALUES(100,201,'Conductor principal');
INSERT INTO TRIPULACION VALUES(100,202,'Conductor secundario');
INSERT INTO TRIPULACION VALUES(100,201,'Conductor');
INSERT INTO TRIPULACION VALUES(100,220,'Terramoza');
GO

select * from TRIPULACION;
go

-- Conclusion: todo mal

-- CASO 2

DROP TABLE TRIPULACION;
GO

CREATE TABLE TRIPULACION(
	IDPROGRAMACION INT NOT NULL,
	IDTRABAJADOR INT NOT NULL,
	COMENTARIO VARCHAR(500),
	CONSTRAINT PK_TRIPULACION PRIMARY KEY(IDPROGRAMACION,IDTRABAJADOR)
);
GO


INSERT INTO TRIPULACION VALUES(100,201,'Conductor principal');
GO

INSERT INTO TRIPULACION VALUES(100,202,'Conductor secundario');
GO

INSERT INTO TRIPULACION VALUES(100,201,'Conductor');
GO

INSERT INTO TRIPULACION VALUES(100,220,'Terramoza');
GO

select * from TRIPULACION;
go

-- Conclusion: todo chevere.


-- CASO 3: Cambios por el DBA

DROP TABLE TRIPULACION;
GO

CREATE TABLE TRIPULACION(
	IDTRIPULACION INT NOT NULL IDENTITY,
	IDPROGRAMACION INT NOT NULL,
	IDTRABAJADOR INT NOT NULL,
	COMENTARIO VARCHAR(500),
	CONSTRAINT PK_TRIPULACION PRIMARY KEY(IDTRIPULACION),
	CONSTRAINT U_TRIPULACION UNIQUE(IDPROGRAMACION,IDTRABAJADOR)
);
GO


INSERT INTO TRIPULACION VALUES(100,201,'Conductor principal');
GO

INSERT INTO TRIPULACION VALUES(100,202,'Conductor secundario');
GO

INSERT INTO TRIPULACION VALUES(100,201,'Conductor');
GO

INSERT INTO TRIPULACION VALUES(100,220,'Terramoza');
GO

select * from TRIPULACION;
go
